- name: Build image
  uses: docker/build-push-action@latest
  with:
    context: .
    push: true
    tags: ${{ steps.meta.outputs.tags }}
    labels: ${{ steps.meta.outputs.labels }}
    secret-envs: |
      TEST_SECRET=TEST_SECRET
